### ISSUE TITLE
Need operand dependency checking

### ISSUE THREAD

**Issue by klingaard** [sparcians/olympia#10]
Olympia has a rename stage, but it's pass through.  Need some form of a scoreboard (like the one proposed [here](https://github.com/sparcians/map/issues/263)) to keep track of dependencies.  The faster, the better.

**Comment by knute-sifive** [comment]
Issue transferred to https://github.com/riscv-software-src/riscv-perf-model/issues/2

**Comment by knute-sifive** [comment]
Zhen, when you accept the invite, you can assign the new issue to yourself.
