### ISSUE TITLE
Need cache models

### ISSUE THREAD

**Issue by klingaard** [sparcians/olympia#11]
Need cache models inserted. Propose an L1 and L2, policies to be run-time configurable. I-cache and D-cache needed.  Possibly can use the cache stuff in Sparta, but it's kinda old.

**Comment by klingaard** [comment]
Also might consider adding Gem5's [Ruby stuff](https://www.gem5.org/documentation/general_docs/ruby/)

**Comment by arupc** [comment]
I can try and tackle this one. Need to make up a simple micro-architecture for the cache. Can certainly use the Sparta cache for functional cache behavior.

**Comment by arupc** [comment]
If there is any suggestion for the cache micro-architecture, please let me know

**Comment by knute-sifive** [comment]
So olympia uses the basic cache structure in Sparta, but probably can be updated with something new.  This issue can be reopened in the new repo: https://github.com/riscv-software-src/riscv-perf-model/issues
