### ISSUE TITLE
Add Mavis to the model

### ISSUE THREAD

**Issue by klingaard** [sparcians/olympia#7]
Need to implement a MavisUnit (or something similar) that will encapsulate Mavis and produce RISCVInst objects to be used in the simulator.  

Mavis: https://github.com/sparcians/mavis

What needs to happen:

- [ ] RISCVAttributes class that encapsulates the static information about a RISC-V instruction and is specific to an opcode (replaces current `sparta::decode::DecoderBase` in the RISCVInst
- [ ] Update `RISCVInst` to accept a pointer (shared) to the RISCVAtrributes
- [ ] Update Mavis to use the above classes

**Comment by peter-d** [comment]
I had a look at Mavis but it was not easy to understand it well, so I've started adding a bit of documentation [here](https://github.com/peter-d/mavis).

At this point I'm using it mostly to document my findings as I walk through the code ( but I might get things wrong!)

**Comment by knute-sifive** [comment]
Thanks for starting that Peter!  @david-murrell is the original author of Mavis and probably can use the help in documenting it.

**Comment by klingaard** [comment]
Hi @peter-d , curious if you have a PR worth putting against Mavis with the documentation...

**Comment by peter-d** [comment]
Whatever I had is in PR #1 in mavis repo. But it’s not much and I don’t have time right now to do more.

**Comment by knute-sifive** [comment]
Oh!  I didn’t know you had a PR!  Fantastic.  Understand completely on the time constraints.  The little (which was a lot) that you did is very good.  I’ll get Dave to look it over.

Thanks again.

**Comment by peter-d** [comment]
You’re welcome. It was just a bunch of commits sitting in my own repo but it’s not nearly up to a level where it is good docs yet. Feel free to merge as is if you like it!

**Comment by knute-sifive** [comment]
Mavis has been added to Olympia
