### ISSUE TITLE
Need to implement a trace reader

### ISSUE THREAD

**Issue by klingaard** [sparcians/olympia#8]
Using https://github.com/sparcians/stf_lib, implement a trace reader that will consume the trace and produce RISCVInst objects to flow down the pipe.

Depends on Mavis implementation #7 

What we will need:
- [ ] A generic reader that will supply `RISCVInsts` from either a given opcode or trace file
- [ ] A wrapper for the trace iterator that can satisfy queries on operand values, positions, branch resolutions, etc

**Comment by klingaard** [comment]
Testing of the trace reader would be helpful once we have a functional model generating traces.  Propose adding the `stf_lib` to the fork of Spike https://github.com/sparcians/spike_trace we have in sparcians

**Comment by knute-sifive** [comment]
STF trace reading was added in PR #18
