### ISSUE TITLE
Add branch predictor

### ISSUE THREAD

**Issue by klingaard** [sparcians/olympia#9]
Need a branch predictor to Fetch.  Open to considerations on the type.  Should be parameterized, but a common API would be beneficial to keep the model generic.  

Resolutions of the branches will require feedback from `Retire` and/or `Execute` .  Typicality this can be done with ports.

**Comment by knute-sifive** [comment]
Transferred to https://github.com/riscv-software-src/riscv-perf-model/issues/1
